model_params:
  learning_rate: 0.05
  max_depth: 4
  n_estimators: 200
  scale_pos_weight: 4

evaluation:
  threshold: 0.35

data_paths:
  raw_data: "data\01-raw-origin.zip"
  processed_data: "data\02-preprocessed-data.csv"
  model_path: "data\05-final-churn-model.joblib"
