name: CI

on: [push,pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Cache Poetry installation (binary)
        id: cache-poetry-binary
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: poetry-2.1.4-${{ runner.os }}

      - name: Install Poetry
        if: steps.cache-poetry-binary.outputs.cache-hit != 'true' 
        uses: snok/install-poetry@v1
        with: 
          version: '2.1.4'
          virtualenvs-create: true
          virtualenvs-in-project: false
          installer-parallel: true
          cache: false

      - name: Load cache Poetry Installation
        id: cached-poetry
        uses: actions/cache@v4
        with:
          path:  ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        
      - name: Install dependencies
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

      - name: Run Ruff Linter 
        run: poetry run ruff check .

      - name: Check Formatting
        run: poetry run ruff format --check .

      



